Modularized layupDesign_ANSYSanalysis.m
sandialabs/NuMAD pull request #8
Opened 2022-03-24 15:05 UTC by rclarke17

Made multiple functions out of layupDesign_ANSYSanalysis.m, added my modified AD2ANSYSfollower.m script that works correctly with NuMAD 3.0

2022-03-28 14:59 UTC, ecamare commented
Hi Ryan, thanks for the pull request. I'd like to keep the function names beginning with a lower case. Is there a reason you preferred uppercase? Have you checked the documentation to make sure the new updates are consistent with what is in the documentation?

2022-03-28 15:11 UTC, rclarke17 commented
I think when I typed it, it was out of habit. We can change it to lower case, that's no issue. Everything else should follow the documentation, I didn't actually change any of the inner workings of the code, just split it into manageable functions.
Best,
Ryan
From: Ernesto Camarena ***@***.***>
Sent: Monday, March 28, 2022 9:00 AM
To: sandialabs/NuMAD ***@***.***>
Cc: Clarke, Ryan ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [sandialabs/NuMAD] Modularized layupDesign_ANSYSanalysis.m (PR #8)


Hi Ryan, thanks for the pull request. I'd like to keep the function names beginning with a lower case. Is there a reason you preferred uppercase? Have you checked the documentation to make sure the new updates are consistent with what is in the documentation?

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsandialabs%2FNuMAD%2Fpull%2F8%23issuecomment-1080763561&data=04%7C01%7Crclarke%40sandia.gov%7Cd98988ec7c2449b4e6ed08da10cba26d%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C637840764037897716%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Yr2b%2B1WAcAn1fRNlxUXMk%2BC66fw0S7la5mj6vzuHkpA%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVW3JD4O327AIJZLNEJLTF3VCHCO5ANCNFSM5RROPO7Q&data=04%7C01%7Crclarke%40sandia.gov%7Cd98988ec7c2449b4e6ed08da10cba26d%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C637840764037897716%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=U2dsD5x9JNf0wmnVAS5Jw0nm4ugSfEZPyxNquvV6xis%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2022-05-02 14:40 UTC, ecamare requested changes
Hi Ryan, 

As i look into the changes more, I realize it is very good to split these out into the respective functions. 

Just a few more things I noticed. The first two comments are potentially very important, the others; not so much: 

-  In the function createANSYS_LocalFieldsResults
    %%%%%%%%%%%%%%%%%%%Outputs for fatigue analysis in MATLAB%%%%%%%%%%%%%%%%%
    fprintf(fid,'! BEGIN LOCAL FIELD SCRIPT\n');
    fprintf(fid,'allsel\n');
    fprintf(fid,'/prep7\n');
    fprintf(fid,'esel,all\n');
    %% RC Addition
    %High Pressure Spar
    fprintf(fid,'esel,s,sect,,3,39,12\n');
    fprintf(fid,'esel,a,sect,,53,389,14\n');

    %Low Pressure Spar
    fprintf(fid,'esel,a,sect,,9,45,12\n');
    fprintf(fid,'esel,a,sect,,59,395,14\n');

I don't think this is robust. If I am not mistaken, if someone changes the definition of the stations, this may not work work very well. 

-I think choosing the word "Perform" in the function name should be replaced by "write". That's what these functions are actually doing. They are writing text to a file. 

- Would you also be able to change the file names so that they match the function names? 
- Remove RJC from the filename and function name of your follower script
- The function names are quite long. How would you feel about removing "Analysis" from most of the function names. 

Below is my recommendation for the function names:

writeAnsysLocalFields
writeAnsysWrinkling (not the spelling correction on wrinkling)
writeAnsysDeflections
writeAnsysRupture 
wirteAnsysFatigue
writeAnsysLinearBuckling
writeAnsysnonLinearBuckling
writeAnsysResultantVSspan
readAnsysDeflections
readAnsysLinearBuckling
readAnsysRupture
writeAnsysGetFaceStresses
writeAnysInputfile
layupDesignAnsysAnalysis (other layupDesign functions have underscores so it would not yet be a unified code).

This makes our code more unified in that it is systematic. it specifies either read or write, all are camel case instead of some with underscores. Before, some functions had Ansys and most had ANSYS. I chose to make them all Ansys since capitalizing ANSYS is cumbersome, anyway. 

You can be honest about how you feel about making the function name changes; let me know.

2022-05-04 13:15 UTC, ecamare approved these changes

2022-05-04 13:16 UTC, merged